// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Login is the predicate function for login builders.
type Login func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
