// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LoginsColumns holds the columns for the "logins" table.
	LoginsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ip", Type: field.TypeString},
		{Name: "device", Type: field.TypeString},
		{Name: "access", Type: field.TypeString},
		{Name: "refresh", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_logins", Type: field.TypeInt, Nullable: true},
	}
	// LoginsTable holds the schema information for the "logins" table.
	LoginsTable = &schema.Table{
		Name:       "logins",
		Columns:    LoginsColumns,
		PrimaryKey: []*schema.Column{LoginsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "logins_users_logins",
				Columns:    []*schema.Column{LoginsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "ip", Type: field.TypeString},
		{Name: "device", Type: field.TypeString},
		{Name: "verified", Type: field.TypeBool, Default: false},
		{Name: "blocked", Type: field.TypeBool, Default: false},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LoginsTable,
		UsersTable,
	}
)

func init() {
	LoginsTable.ForeignKeys[0].RefTable = UsersTable
}
