// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/mars1385/e-com-go/auth/ent/login"
	"github.com/mars1385/e-com-go/auth/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LoginCreate is the builder for creating a Login entity.
type LoginCreate struct {
	config
	mutation *LoginMutation
	hooks    []Hook
}

// SetIP sets the "ip" field.
func (lc *LoginCreate) SetIP(s string) *LoginCreate {
	lc.mutation.SetIP(s)
	return lc
}

// SetDevice sets the "device" field.
func (lc *LoginCreate) SetDevice(s string) *LoginCreate {
	lc.mutation.SetDevice(s)
	return lc
}

// SetAccess sets the "access" field.
func (lc *LoginCreate) SetAccess(s string) *LoginCreate {
	lc.mutation.SetAccess(s)
	return lc
}

// SetRefresh sets the "refresh" field.
func (lc *LoginCreate) SetRefresh(s string) *LoginCreate {
	lc.mutation.SetRefresh(s)
	return lc
}

// SetCreatedAt sets the "created_at" field.
func (lc *LoginCreate) SetCreatedAt(t time.Time) *LoginCreate {
	lc.mutation.SetCreatedAt(t)
	return lc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (lc *LoginCreate) SetNillableCreatedAt(t *time.Time) *LoginCreate {
	if t != nil {
		lc.SetCreatedAt(*t)
	}
	return lc
}

// SetUpdatedAt sets the "updated_at" field.
func (lc *LoginCreate) SetUpdatedAt(t time.Time) *LoginCreate {
	lc.mutation.SetUpdatedAt(t)
	return lc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (lc *LoginCreate) SetNillableUpdatedAt(t *time.Time) *LoginCreate {
	if t != nil {
		lc.SetUpdatedAt(*t)
	}
	return lc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (lc *LoginCreate) SetUserID(id int) *LoginCreate {
	lc.mutation.SetUserID(id)
	return lc
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (lc *LoginCreate) SetNillableUserID(id *int) *LoginCreate {
	if id != nil {
		lc = lc.SetUserID(*id)
	}
	return lc
}

// SetUser sets the "user" edge to the User entity.
func (lc *LoginCreate) SetUser(u *User) *LoginCreate {
	return lc.SetUserID(u.ID)
}

// Mutation returns the LoginMutation object of the builder.
func (lc *LoginCreate) Mutation() *LoginMutation {
	return lc.mutation
}

// Save creates the Login in the database.
func (lc *LoginCreate) Save(ctx context.Context) (*Login, error) {
	lc.defaults()
	return withHooks(ctx, lc.sqlSave, lc.mutation, lc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (lc *LoginCreate) SaveX(ctx context.Context) *Login {
	v, err := lc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lc *LoginCreate) Exec(ctx context.Context) error {
	_, err := lc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lc *LoginCreate) ExecX(ctx context.Context) {
	if err := lc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lc *LoginCreate) defaults() {
	if _, ok := lc.mutation.CreatedAt(); !ok {
		v := login.DefaultCreatedAt()
		lc.mutation.SetCreatedAt(v)
	}
	if _, ok := lc.mutation.UpdatedAt(); !ok {
		v := login.DefaultUpdatedAt()
		lc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lc *LoginCreate) check() error {
	if _, ok := lc.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "Login.ip"`)}
	}
	if _, ok := lc.mutation.Device(); !ok {
		return &ValidationError{Name: "device", err: errors.New(`ent: missing required field "Login.device"`)}
	}
	if _, ok := lc.mutation.Access(); !ok {
		return &ValidationError{Name: "access", err: errors.New(`ent: missing required field "Login.access"`)}
	}
	if _, ok := lc.mutation.Refresh(); !ok {
		return &ValidationError{Name: "refresh", err: errors.New(`ent: missing required field "Login.refresh"`)}
	}
	if _, ok := lc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Login.created_at"`)}
	}
	if _, ok := lc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Login.updated_at"`)}
	}
	return nil
}

func (lc *LoginCreate) sqlSave(ctx context.Context) (*Login, error) {
	if err := lc.check(); err != nil {
		return nil, err
	}
	_node, _spec := lc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	lc.mutation.id = &_node.ID
	lc.mutation.done = true
	return _node, nil
}

func (lc *LoginCreate) createSpec() (*Login, *sqlgraph.CreateSpec) {
	var (
		_node = &Login{config: lc.config}
		_spec = sqlgraph.NewCreateSpec(login.Table, sqlgraph.NewFieldSpec(login.FieldID, field.TypeInt))
	)
	if value, ok := lc.mutation.IP(); ok {
		_spec.SetField(login.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := lc.mutation.Device(); ok {
		_spec.SetField(login.FieldDevice, field.TypeString, value)
		_node.Device = value
	}
	if value, ok := lc.mutation.Access(); ok {
		_spec.SetField(login.FieldAccess, field.TypeString, value)
		_node.Access = value
	}
	if value, ok := lc.mutation.Refresh(); ok {
		_spec.SetField(login.FieldRefresh, field.TypeString, value)
		_node.Refresh = value
	}
	if value, ok := lc.mutation.CreatedAt(); ok {
		_spec.SetField(login.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := lc.mutation.UpdatedAt(); ok {
		_spec.SetField(login.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := lc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   login.UserTable,
			Columns: []string{login.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_logins = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LoginCreateBulk is the builder for creating many Login entities in bulk.
type LoginCreateBulk struct {
	config
	err      error
	builders []*LoginCreate
}

// Save creates the Login entities in the database.
func (lcb *LoginCreateBulk) Save(ctx context.Context) ([]*Login, error) {
	if lcb.err != nil {
		return nil, lcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(lcb.builders))
	nodes := make([]*Login, len(lcb.builders))
	mutators := make([]Mutator, len(lcb.builders))
	for i := range lcb.builders {
		func(i int, root context.Context) {
			builder := lcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LoginMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lcb *LoginCreateBulk) SaveX(ctx context.Context) []*Login {
	v, err := lcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lcb *LoginCreateBulk) Exec(ctx context.Context) error {
	_, err := lcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcb *LoginCreateBulk) ExecX(ctx context.Context) {
	if err := lcb.Exec(ctx); err != nil {
		panic(err)
	}
}
